#Dado el diccionario precios_frutas
#precios_frutas = {'Banana': 1200, 'Ananá': 2500, 'Melón': 3000, 'Uva':1450}
#Añadir las siguientes frutas con sus respectivos precios:
#● Naranja = 1200
#● Manzana = 1500
#● Pera = 2300

#creamos el diccionario con las key-value 
precios_frutas = {'Banana': 1200, 'Anana': 2500, 'Melon' : 3000, 'Uva': 1450}

#agregamos las frutas y sus precios que pide la consigna
precios_frutas['Naranja'] = 1200
precios_frutas['Manzana'] = 1500
precios_frutas['Pera'] = 2300
#imprimimos por pantalla el diccionario con los nuevos valores
print(precios_frutas)